### ISSUE TITLE
webhook tidak ada respon

### ISSUE THREAD

**Issue by wandy001** [oka-wiadnyana/whatsappbot-php-simple#1]
saya mencoba menggunakan bowebhook yang langsung menembak ke indek kenapa tidak ada respon nya

		{
			"contains": ["tilang#"],
			"exact": ["tilang#"],
			"webhook": "http://192.168.2.3/wabot/index.php",

		}
	],

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/141445218-8da450d2-8506-49d2-81ac-9e950bfa7719.png)

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/141447024-bc55dfd0-46e9-40b4-8ed6-c867bc544b3c.png)

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/141447133-06a46519-29d0-4cd1-b9b4-c392b34c24bf.png)

**Comment by oka-wiadnyana** [comment]
Bot.json yg di downloadan wbot ckup ganti dengan bot.json di repo saya pak..ckup gnti alamatnya sesuai ip server

**Comment by oka-wiadnyana** [comment]
Silhkn bisa lewat telegram pak..kalau misalnya ada kendala..biar lbih mudah

**Comment by wandy001** [comment]
kemarin sudah di coba tpi masih belum bisa bu,,

**Comment by wandy001** [comment]
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..
Processing global webhook
Message from 6281278146663 checking..

**Comment by oka-wiadnyana** [comment]
iya coba nnti bisa diremote..inboks ke messenger ya pak

**Comment by wandy001** [comment]
saya coba terlebih dahulu bu

**Comment by wandy001** [comment]
servernya apakah bisa langsu nembah ke server atau xampp

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/141944025-f3dd69bd-98a0-4779-9f12-a404fd69ab4e.png)

saya cek di xampp erornya begini bu

**Comment by oka-wiadnyana** [comment]
bapak coba dlu apakah dbnya jalan apa ngga..silahkan buat fle baru di folder public untuk mencoba...dan tuliskan script dibawah :

<?php  
include 'data.php';

$data = new Data;
$tanggal = $data->get_jadwal_sidang('nomor perkara'); //ganti nomor perkara dengan perkara yang ada di pn

echo $tanggal;

?>

**Comment by wandy001** [comment]
ada contohnya bu di PN Ibu

Pada tanggal Rab, 17 Nov 2021 03.58, oka-wiadnyana ***@***.***>
menulis:

**Comment by oka-wiadnyana** [comment]
Cba mnggu depan ya pak..saya remote..inbok aja di telegram

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/144350473-c89d0866-d8a5-43a6-864c-7855ef9f1533.png) kalau db nya jalan bu,, kalau firewal di komputer apakah ngaruh bu

**Comment by wandy001** [comment]
terimakasih bu sudah bisa... hanya saja untuk perkara tilang keterangan nya Data tidak ditemukan

**Comment by oka-wiadnyana** [comment]
Coba cek pak..apakah nomor plat di sipp ada spasi atau tidak...krena kbtulan di satker kami nomor plat tidak pake spasi..atau kalo mau custom pencarian berdasarkan nomor tilang

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/144524336-e5d647a9-699c-4930-b2a9-678f286a2479.png)

**Comment by wandy001** [comment]
tidak bu tidak ada spasinya,,,

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/144524751-14476dd4-89cb-45da-9c14-54e6df656ce7.png)

**Comment by wandy001** [comment]
kalau custom nya saya coba ngak bisa bu berdasarkan nomor tilang,,,, kemarin saya coba nomor tilang nya bu.... bukan berdasarkan plat nya,

**Comment by wandy001** [comment]
![image](https://user-images.githubusercontent.com/7680924/144525018-2fc9eb08-0908-46d1-a60b-55ba732dd5bf.png)

**Comment by wandy001** [comment]
sudah saya edit bu di idnya sudah bisa, terimakasih banyak bu, ilmu nya

**Comment by oka-wiadnyana** [comment]
Ok gan saya close

**Comment by oka-wiadnyana** [comment]
Ok gan saya close ya

**Comment by wandy001** [comment]
terimakasih bu
